### ISSUE TITLE
iPad Dock - control number of Recents/Suggestions

### ISSUE THREAD

**Issue by ahanank** [tomaszpoliszuk/DockController#3]
Could there be an option to add minimum/maximum recent/suggestive apps when using the iPad dock?

**Comment by tomaszpoliszuk** [comment]
Yes - it will be part of one of future updates (i have currently test suggestions part - recents are ready).
I will leave it open until i publish this feature :)

**Comment by tomaszpoliszuk** [comment]
@ahanank do you have suggestions visible on your device?

**Comment by ahanank** [comment]
I’m not using it right now but when it did, no. They are gonna have to be forced. Apple messed up on iOS 13 and they never show up, even on an iPad. So..something changed from iOS 12 (they worked there, even with FDP13) and now they don’t.

**Comment by tomaszpoliszuk** [comment]
Do you have some link where this issue is described?

I will soon send updated version that have few new features - ability to control number of Recents will be among them.

**Comment by ahanank** [comment]
There’s no link to it. It’s just known, it got fixed on iOS 14.

**Comment by tomaszpoliszuk** [comment]
Ok, thank you for letting me know (I didn't know that).

I've just sent version 1.1 - it will be available on BigBoss repo as soon as Optimo check and approve it.

If you wish to try it sooner you can download it from [here](https://github.com/tomaszpoliszuk/DockController/releases/download/1.1/com.tomaszpoliszuk.dockcontroller_1.1_iphoneos-arm.deb).

I'm closing this issue since ability to control number of recent is implemented.
